name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup CMake
        uses: jwlawson/actions-setup-cmake@v2
        with:
          cmake-version: '3.22'
      - name: Download minunit.h
        run: wget https://raw.githubusercontent.com/siu/minunit/refs/heads/master/minunit.h
      - name: Configure
        run: cmake -B build
      - name: Build drawer
        run: cmake --build build --target drawer
      - name: Build tests
        run: cmake --build build --target tests
      - name: Run tests
        run: ./build/tests
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: drawer-executable
          path: build/drawer
